POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmQ3ZTNjYTQyNGMyMmUyZTE0NzNiMyIsImlhdCI6MTY5NzUyODI5NX0.BKHjIdkfsR3pTW6ce4O3VY-dmgy1Sj5ROdqjGgxD4Ls

{
    "title": "Tech Crunch",
    "author": "Tech Crunch", 
    "url": "https://techcrunch.com/",
    "likes": 1000
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Bright Bazaar",
    "author": "Will Taylor",
    "url": "https://www.brightbazaarblog.com/",
    "likes": 7,
    "userId": "652d7e3ca424c22e2e1473b3"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Cup of Jo",
    "author": "Joanna Goddard",
    "url": "https://cupofjo.com/",
    "likes": 5,
    "userId": "652d7e3ca424c22e2e1473b3"
}

###
PUT http://localhost:3003/api/blogs/6523ec580020bc2b46e4d5ab
Content-Type: application/json

{
    "title": "Savoury Days",
    "author": "Linh Trang", 
    "url": "http://www.savourydays.com/",
    "likes": 1000
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "admin",
    "name": "Administrator",
    "password": "GoForAPassword"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "user1",
    "name": "User1",
    "password": "LetKeepThisASecret"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "user3",
    "name": "Lady Minh",
    "password": "Nothing"
}
