POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoaXBoYWlnaW8iLCJpZCI6IjYwZDBlMjgxYmIzYjY4MzZlODUxNzFiMCIsImlhdCI6MTYyNTAzMTUzMCwiZXhwIjoxNjI1MDM1MTMwfQ.kjvEYvPM4baYhQ9nnOa0Heq7VGrL_Bg-bGdmexNptZs

{
    "title":"Khong biet nua",
    "author":"Linh Trang",
    "url":"https://giangoi.com/blog/",
    "likes":3268
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoaXBoYWlnaW8iLCJpZCI6IjYwZDBlMjgxYmIzYjY4MzZlODUxNzFiMCIsImlhdCI6MTYyNTAzMTkyNSwiZXhwIjoxNjI1MDM1NTI1fQ.pzvMAu6MSMzh9vlvpHFVqxqk3nhtM86RRqSyLNpU_nI

{
    "title":"Moi dieu chua noi",
    "author":"Minh Giang",
    "url":"https://giangoi.com/blog/",
    "likes":10000
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title":"Savoury days",
    "author":"Linh Trang",
    "url":"http://www.savourydays.com/",
    "likes":100
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title":"Wb Desginer Depot",
    "author":"Unknown",
    "url":"https://www.webdesignerdepot.com/",
    "likes":1000
}