POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes":[],
    "username": "root",
    "name":"Superuser",
    "password": "password"
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes":[],
    "username": "khiphaigio",
    "name":"Con Khi Gio",
    "password": "khivagio"
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes":[],
    "username": "root",
    "name":"Superuser",
    "password": "password"
}

### 
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes":[],
    "username": "giagia",
    "name":"Thu Giang",
    "password": "giangthu"
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "notes":[],
    "username": "linhtrang",
    "name":"Tran Linh Trang",
    "password": "tranglinh"
}