POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpYWdpYSIsImlkIjoiNjBkMGUzZDA2NTMwOGExMzJjNGE4MjkzIiwiaWF0IjoxNjI0NTI1NjMxLCJleHAiOjE2MjQ1MjkyMzF9.tKo6HGffB0rz_5a3g1vPNBPBD-IBdCU7fwHBytClduE

{
    "title":"Khong biet nua",
    "author":"Linh Trang",
    "url":"https://giangoi.com/blog/",
    "likes":3268,
    "userId": "60892abb6000df0a14e22ab6"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdpYWdpYSIsImlkIjoiNjBkMGUzZDA2NTMwOGExMzJjNGE4MjkzIiwiaWF0IjoxNjI0NTI1NjMxLCJleHAiOjE2MjQ1MjkyMzF9.tKo6HGffB0rz_5a3g1vPNBPBD-IBdCU7fwHBytClduE

{
    "title":"Co em doi bong vui",
    "author":"Tran Thi Thu Giang",
    "url":"https://giangoi.com/blog/",
    "likes":10000,
    "userId": "60d0e281bb3b6836e85171b0"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title":"Savoury days",
    "author":"Linh Trang",
    "url":"http://www.savourydays.com/",
    "likes":100
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title":"Wb Desginer Depot",
    "author":"Unknown",
    "url":"https://www.webdesignerdepot.com/",
    "likes":1000
}