###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "giagia",
    "password": "giangthu"
}

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "linhtrang",
    "password": "tranglinh"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "khiphaigio",
    "password": "khivagio"
}