###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "giagia",
    "password": "giangthu"
}

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "linhtrang",
    "password": "tranglinh"
}