POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "content": "VS Test",
    "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Tala Test",
    "important": false
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Elino Elon",
    "number": "03-49-3256328"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Maza Edison",
    "number": "050-38-3689"
}

###
DELETE http://localhost:3001/api/persons/604a010cd94f93258cb0ba82

###
PUT http://localhost:3001/api/persons/604a00abb561a60d44c20d6c
Content-Type: application/json

{
    "name": "Mimi",
    "number": "015-58-92894"
}