GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/604a00abb561a60d44c20d6c

###
GET http://localhost:3001/api/persons/604a010cd94f93258cb0ba82
